
create table "user" (
                        id int generated by default as identity primary key ,
                        name varchar unique not null ,
                        age int check ( age > 17 )
);

